export type Dimension = 'accuracy' | 'freshness' | 'conflict_resolution' | 'appropriate_use';
export type MemoryStatus = 'candidate' | 'confirmed' | 'edited' | 'rejected';
export type RelationshipType = 'UPDATE'|'CONFLICT'|'CONTEXTUAL_OVERRIDE';
export interface ConversationMessage { message_id:string; role:string; content:string; timestamp:string }
export interface ConversationInputMessage { message_id?:string; role:string; content:string; timestamp?:string }
export interface Conversation { conversation_id:string; created_at:string; authorised:boolean; messages:ConversationMessage[] }
export interface ConversationDeletionReceipt { conversation_id:string; deleted_audit_runs:number; deleted_experiments:number; message:string }
export interface MemoryRelationship { relationship_id?:string; type:RelationshipType; target_memory_id:string }
export interface Memory { memory_id:string; conversation_id:string; canonical_value:string; status:MemoryStatus; source_message_ids:string[]; timestamp?:string; relationships:MemoryRelationship[] }
export interface MemoryReviewPatch { canonical_value?:string; status?:MemoryStatus; source_message_ids?:string[]; timestamp?:string; relationships?:MemoryRelationship[] }
export type TargetProvider = 'rule_based'|'openai'|'deepseek'|'gemini';
export type MemoryStrategy = 'weak_first_hit'|'strong_rule_based'|'strong_score_based'|'scope_aware'|'temporal_importance';
export type MemoryMaintenancePolicy = 'append_only'|'update_aware_consolidation';
export type TargetMemoryWriterKind = 'rule_based'|'llm_structured';
export type TestSuiteMode = 'behavioural'|'direct_ground_truth'|'fixed_template';
export type TestType = 'direct'|'contextual'|'paraphrased'|'indirect';
export type TestQualityStatus = 'pending'|'accepted'|'rejected';
export type GroundingStatus = 'pending'|'grounded'|'ungrounded';
export interface RetryPolicyMetadata { max_attempts:number; timeout_seconds:number; retryable_status_codes:number[] }
export interface AuditRetryPlan { run_id:string; next_stage:'generate_tests'|'execute_tests'|'evaluate_responses'|null; pending:number; retryable:boolean }
export interface ReproducibilityMetadata { schema_version:string; configuration_fingerprint?:string|null; prompt_template_fingerprint?:string|null; target_memory_writer_version?:string|null; target_system_adapter?:string; target_system_adapter_version?:string|null; memory_policy_version?:string|null; seed_control?:Record<string,string>; target_retry_policy:RetryPolicyMetadata }
export interface ExecutionMetadata { request_attempts:number; latency_ms?:number|null; input_tokens?:number|null; output_tokens?:number|null; total_tokens?:number|null; response_source:string }
export interface Experiment { experiment_id:string; conversation_id:string; label:string; status:string; test_suite_configuration:{test_budget:number;random_seed:number;prompt_template_version:string;pipeline_provider:TargetProvider;pipeline_model:string;dimensions:Dimension[];suite_mode:TestSuiteMode}; test_suite_metadata:{test_count:number;dimensions:Dimension[];generator_version?:string;generated_at?:string}; test_suite_source_run_id?:string; created_at:string; completed_at?:string }
export interface AuditRun { run_id:string; conversation_id:string; experiment_id?:string; status:string; target_configuration:'weak'|'strong'; provider:TargetProvider; model:string; temperature:number; random_seed:number; test_budget:number; prompt_template_version:string; pipeline_provider:string; pipeline_model:string; evaluator_provider:string; evaluator_model:string; memory_strategy:MemoryStrategy; memory_maintenance_policy?:MemoryMaintenancePolicy; target_memory_capacity?:number; target_memory_writer?:TargetMemoryWriterKind; target_memory_writer_version?:string|null; reproducibility?:ReproducibilityMetadata; created_at:string; completed_at?:string }
export interface ProviderOption { provider:TargetProvider; label:string; default_model:string; configured:boolean; description:string }
export interface TestCase { test_id:string; run_id:string; dimension:Dimension; prompt:string; expected_behavior:string; supporting_memory_ids:string[]; generator_version:string; test_type?:TestType; quality_status?:TestQualityStatus; grounding_status?:GroundingStatus; validation_notes?:string }
export interface TestReviewSuite { run_id:string; canonical_run_id:string; tests:TestCase[] }
export interface TargetMemoryTraceRecord { memory_id:string; canonical_value:string; scope:'profile'|'preference'|'project_requirement'|'episodic'; lifecycle_state:'ACTIVE'|'SUPERSEDED'|'CONFLICTED'|'EVICTED'; source_message_ids:string[]; observed_at?:string; write_order:number; relationships:MemoryRelationship[] }
export interface TargetMemoryTraceEvent { event_id:string; event_type:'INGESTED'|'WRITTEN'|'UPDATED'|'MAINTENANCE_APPLIED'|'CONFLICT_RECORDED'|'CONTEXTUAL_OVERRIDE_RECORDED'|'RETRIEVED'; memory_id?:string; source_message_ids:string[]; details:Record<string, unknown>; created_at:string }
export interface TargetMemoryTraceRetrieval { retrieval_id:string; test_id:string; strategy:MemoryStrategy; selected_memory_ids:string[]; ranking_evidence:Array<Record<string, unknown>>; created_at:string }
export interface TargetMemoryTrace { run_id:string; memory_strategy:MemoryStrategy; memory_maintenance_policy:'append_only'|'update_aware_consolidation'; target_memory_capacity?:number; target_memory_writer?:TargetMemoryWriterKind; target_memory_writer_version?:string|null; records:TargetMemoryTraceRecord[]; events:TargetMemoryTraceEvent[]; retrievals:TargetMemoryTraceRetrieval[] }
export interface TargetResponse { response_id:string; test_id:string; run_id:string; response_text:string; model:string; temperature:number; execution_metadata?:ExecutionMetadata; created_at:string }
export interface EvaluationResult { evaluation_id:string; test_id:string; response_id:string; passed:boolean; failure_type?:Dimension; reason:string; evidence_memory_ids:string[]; evaluator:string }
export type HumanReviewRole = 'independent'|'reference'|'adjudication';
export interface EvaluationHumanReview { review_id:string; evaluation_id:string; human_passed:boolean; human_failure_type?:Dimension|null; reviewer_label:string; review_role:HumanReviewRole; based_on_review_ids:string[]; note?:string|null; created_at:string; updated_at:string }
export interface EvaluationReviewItem { test:TestCase; response:TargetResponse; automated:EvaluationResult; human_review?:EvaluationHumanReview|null; human_reviews:EvaluationHumanReview[] }
export interface EvaluationCalibrationSummary { run_id:string; automated_failure_count:number; human_reviewed_count:number; agreement_count:number; disagreement_count:number; agreement_percentage:number|null; failure_precision:number|null; failure_recall:number|null; failure_f1:number|null; by_dimension:Record<string,{reviewed:number;agreement:number;automated_failures:number;human_failures:number}>; independent_review_count:number; independently_reviewed_evaluation_count:number; independent_consensus_count:number; independent_conflict_count:number; independent_pair_count:number; independent_pair_agreement_percentage:number|null; independent_pair_kappa:number|null }
export interface DimensionScores { dimension:Dimension; percentage:number | null; passed:number; total:number }
export interface RetrievalQualityScores { tests_measured:number; evidence_recall_at_k:number|null; evidence_precision_at_k:number|null; update_evidence_recall:number|null; conflict_evidence_coverage:number|null; unnecessary_memory_retrieval_rate:number|null }
export interface FailureDetail { failure_id:string; test:TestCase; response:TargetResponse; evaluation:EvaluationResult; evidence:Memory[] }
export interface AuditResult { run_id:string; overall_score:number|null; tests_passed:number; tests_total:number; dimensions:DimensionScores[]; failures:FailureDetail[]; retrieval_quality?:RetrievalQualityScores; reproducibility?:ReproducibilityMetadata }
export interface ExperimentResult { experiment_id:string; label:string; weak_score:number; strong_score:number; notes:string }
export interface ExperimentDimensionSummary { dimension:Dimension; mean_percentage:number|null; standard_deviation:number|null; passed:number; total:number; measured_runs:number }
export interface ExperimentConditionSummary { condition_id:string; label:string; provider:TargetProvider; model:string; memory_strategy:MemoryStrategy; planned_runs:number; completed_runs:number; failed_runs:number; run_ids:string[]; overall_mean:number|null; overall_standard_deviation:number|null; tests_passed:number; tests_total:number; failure_count:number; dimensions:ExperimentDimensionSummary[] }
export interface PairedComparison { reference_run_id:string; reference_label:string; candidate_run_id:string; candidate_label:string; shared_tests:number; both_passed:number; both_failed:number; reference_only_passed:number; candidate_only_passed:number; candidate_delta_percentage_points:number|null; candidate_delta_confidence_interval_low:number|null; candidate_delta_confidence_interval_high:number|null; two_sided_sign_test_p_value:number|null }
export interface ExperimentRunReport { run:AuditRun; result:AuditResult|null }
export interface ExperimentAnalytics { experiment:Experiment; runs:ExperimentRunReport[]; conditions:ExperimentConditionSummary[]; paired_comparisons:PairedComparison[] }
export interface AnnotationImportReport { dataset_id:string; dataset_version:string; fingerprint_sha256:string; conversations:number; gold_memories:number; gold_relationships:number; gold_tests:number; gold_evaluations:number; created_at:string; validation_status:string }
export interface BinaryClassificationMetrics { labelled_cases:number; true_positives:number; false_positives:number; true_negatives:number; false_negatives:number; precision:number|null; recall:number|null; f1:number|null; accuracy:number|null; false_positive_rate:number|null; cohens_kappa:number|null }
export interface ResearchValidityReport { dataset_id:string; dataset_version:string; conversations:number; extraction:BinaryClassificationMetrics; relationship:BinaryClassificationMetrics; test_validity:BinaryClassificationMetrics; evaluator:BinaryClassificationMetrics }
export interface LongMemEvalImportReport { adapter_version:string; cases_imported:number; case_ids:string[]; dimension_hints:string[]; source_format:string; notice:string }
export interface LongMemEvalValidationResponse { report:LongMemEvalImportReport; cases:Array<{case_id:string; question:string; expected_answer:string; category:string; dimension_hint?:string|null}> }
export interface BenchmarkScoreSummary { key:string; passed:number; total:number; percentage:number|null }
export interface LongMemEvalRunResponse { metadata:{run_id:string; runner_version:string; source_fingerprint_sha256:string; source_label?:string|null; memory_strategy:MemoryStrategy; notice:string}; cases:Array<{case_id:string; category:string; dimension?:Dimension|null; question:string; response_text:string; passed:boolean; evaluation_reason:string; retrieved_memory_ids:string[]}>; categories:BenchmarkScoreSummary[]; dimensions:BenchmarkScoreSummary[]; tests_passed:number; tests_total:number; overall_percentage:number|null }
export type BenchmarkFamily = 'longmemeval'|'locomo'|'beam';
export interface BenchmarkCasePreview { case_id:string; question:string; expected_answer:string; category:string; dimension_hint?:string|null }
export interface LocalCompatibleImportReport { benchmark_family:BenchmarkFamily; adapter_version:string; cases_imported:number; case_ids:string[]; dimension_hints:string[]; source_format:string; notice:string }
export interface LocalCompatibleValidationResponse { report:LocalCompatibleImportReport; cases:BenchmarkCasePreview[] }
export type BenchmarkValidationResponse = LongMemEvalValidationResponse | LocalCompatibleValidationResponse;
export interface BenchmarkRunMetadata { run_id:string; runner_version:string; adapter_version?:string; source_fingerprint_sha256:string; source_label?:string|null; memory_strategy:MemoryStrategy; notice:string; benchmark_family?:BenchmarkFamily; random_seed?:number; source_format?:string }
export interface BenchmarkCaseRunResult { case_id:string; category:string; dimension?:Dimension|null; question:string; expected_answer?:string; response_text:string; passed:boolean; evaluation_reason:string; ingested_memory_count?:number; retrieved_memory_ids:string[]; retrieval_evidence?:Array<Record<string, unknown>> }
export interface LocalCompatibleRunResponse { metadata:BenchmarkRunMetadata; cases:BenchmarkCaseRunResult[]; categories:BenchmarkScoreSummary[]; dimensions:BenchmarkScoreSummary[]; tests_passed:number; tests_total:number; overall_percentage:number|null }
export type BenchmarkRunResponse = LongMemEvalRunResponse | LocalCompatibleRunResponse;
export type PilotTask = 'memory_inclusion'|'relationship_type'|'test_validity'|'evaluator_verdict'|'failure_dimension';
export interface PilotAgreementMetrics { task:PilotTask|null; declared_items:number; annotator_a_labelled:number; annotator_b_labelled:number; paired_items:number; adjudicated_items:number; agreement_count:number; disagreement_count:number; percent_agreement:number|null; cohens_kappa:number|null; kappa_applicable:boolean; disagreements_adjudicated:number; unresolved_disagreements:number }
export interface PilotReadinessReport { pilot_id:string; dataset_id:string; dataset_version:string; fingerprint_sha256:string; annotator_ids:string[]; minimum_paired_items_per_task:number; minimum_kappa:number|null; overall:PilotAgreementMetrics; by_task:PilotAgreementMetrics[]; ready_for_formal_evaluation:boolean; blocking_reasons:string[]; retention:string }
