"""initial foundation schema

Revision ID: 0001_initial
"""
from alembic import op
import sqlalchemy as sa
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('conversations',sa.Column('id',sa.String(40),primary_key=True),sa.Column('authorised',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False))
    op.create_table('messages',sa.Column('id',sa.String(40),primary_key=True),sa.Column('conversation_id',sa.String(40),sa.ForeignKey('conversations.id',ondelete='CASCADE'),nullable=False),sa.Column('role',sa.String(20),nullable=False),sa.Column('content',sa.Text(),nullable=False),sa.Column('timestamp',sa.DateTime(),nullable=False))
    op.create_table('memories',sa.Column('id',sa.String(40),primary_key=True),sa.Column('conversation_id',sa.String(40),sa.ForeignKey('conversations.id',ondelete='CASCADE'),nullable=False),sa.Column('canonical_value',sa.Text(),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('source_message_ids',sa.JSON(),nullable=False),sa.Column('timestamp',sa.DateTime(),nullable=True))
    op.create_table('memory_relationships',sa.Column('id',sa.String(40),primary_key=True),sa.Column('memory_id',sa.String(40),sa.ForeignKey('memories.id',ondelete='CASCADE'),nullable=False),sa.Column('relationship_type',sa.String(30),nullable=False),sa.Column('target_memory_id',sa.String(40),sa.ForeignKey('memories.id',ondelete='CASCADE'),nullable=False))
    op.create_table('audit_runs',sa.Column('id',sa.String(40),primary_key=True),sa.Column('conversation_id',sa.String(40),sa.ForeignKey('conversations.id'),nullable=False),sa.Column('status',sa.String(40),nullable=False),sa.Column('target_configuration',sa.String(20),nullable=False),sa.Column('model',sa.String(100),nullable=False),sa.Column('temperature',sa.Float(),nullable=False),sa.Column('random_seed',sa.Integer(),nullable=False),sa.Column('test_budget',sa.Integer(),nullable=False),sa.Column('prompt_template_version',sa.String(40),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('completed_at',sa.DateTime(),nullable=True))
    op.create_table('test_cases',sa.Column('id',sa.String(40),primary_key=True),sa.Column('run_id',sa.String(40),sa.ForeignKey('audit_runs.id',ondelete='CASCADE'),nullable=False),sa.Column('dimension',sa.String(30),nullable=False),sa.Column('prompt',sa.Text(),nullable=False),sa.Column('expected_behavior',sa.Text(),nullable=False),sa.Column('supporting_memory_ids',sa.JSON(),nullable=False),sa.Column('generator_version',sa.String(40),nullable=False))
    op.create_table('target_responses',sa.Column('id',sa.String(40),primary_key=True),sa.Column('test_id',sa.String(40),sa.ForeignKey('test_cases.id',ondelete='CASCADE'),nullable=False),sa.Column('run_id',sa.String(40),sa.ForeignKey('audit_runs.id',ondelete='CASCADE'),nullable=False),sa.Column('response_text',sa.Text(),nullable=False),sa.Column('model',sa.String(100),nullable=False),sa.Column('temperature',sa.Float(),nullable=False),sa.Column('created_at',sa.DateTime(),nullable=False))
    op.create_table('evaluation_results',sa.Column('id',sa.String(40),primary_key=True),sa.Column('test_id',sa.String(40),sa.ForeignKey('test_cases.id',ondelete='CASCADE'),nullable=False),sa.Column('response_id',sa.String(40),sa.ForeignKey('target_responses.id',ondelete='CASCADE'),nullable=False),sa.Column('passed',sa.Boolean(),nullable=False),sa.Column('failure_type',sa.String(40),nullable=True),sa.Column('reason',sa.Text(),nullable=False),sa.Column('evidence_memory_ids',sa.JSON(),nullable=False),sa.Column('evaluator',sa.String(40),nullable=False))
def downgrade():
    for name in ['evaluation_results','target_responses','test_cases','audit_runs','memory_relationships','memories','messages','conversations']: op.drop_table(name)
