"""Build a blank independent review pack from saved development evidence.

Reads local exports only. Never calls the audit API, writes database records,
or fills human labels. The private mapping must not be sent to reviewers.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(',', ':')).encode()).hexdigest()


def build(source, destination):
    destination.mkdir(parents=True, exist_ok=True)
    if source.get('human_labels') != 0:
        raise ValueError('This release is designed for an unlabelled development pilot.')
    contexts, cases, mapping = {}, [], []
    tasks = {
        'memory_inclusion': ['include', 'exclude'],
        'relationship_type': ['none', 'UPDATE', 'CONFLICT', 'CONTEXTUAL_OVERRIDE'],
        'test_validity': ['accept', 'reject'],
        'evaluator_verdict': ['pass', 'fail'],
        'failure_dimension': ['none', 'accuracy', 'freshness', 'conflict_resolution', 'appropriate_use'],
    }

    def add(task, context, content, private):
        identity = f'ITEM-{len(cases) + 1:04}'
        cases.append({'item_id': identity, 'task': task, 'scenario': context,
                      'evidence': content, 'allowed_labels': tasks[task],
                      'label': None, 'decision_note': None})
        mapping.append({'item_id': identity, 'task': task, **private})

    for number, (conversation_id, history) in enumerate(source['sources'].items(), 1):
        context = f'Scenario {number}'
        messages = history['messages']
        names = {message['id']: f'Message {i + 1}' for i, message in enumerate(messages)}
        names.update({message.get('source_message_id'): f'Message {i + 1}' for i, message in enumerate(messages) if message.get('source_message_id')})
        contexts[context] = {
            'messages': [{'message': f'Message {i + 1}', 'role': message['role'],
                          'text': message['content'], 'timestamp': message['timestamp']}
                         for i, message in enumerate(messages)],
            'missing_memory_notes': None,
            'human_reference_corrections': None,
        }
        candidates = {memory['id']: memory for memory in history['candidates']}
        for memory in candidates.values():
            add('memory_inclusion', context, {
                'candidate_fact': memory['canonical_value'],
                'source_messages': [names.get(identity, 'Unresolved source reference') for identity in memory['source_message_ids']],
            }, {'conversation_id': conversation_id, 'candidate': memory})
        proposed = {(relationship['memory_id'], relationship['target_memory_id']): relationship
                    for relationship in history['relationships']}
        pairs = list(proposed)
        # Include unproposed pairs without assuming that their human label is none.
        other_pairs = sorted([(left, right) for left in candidates for right in candidates
                              if left != right and (left, right) not in proposed],
                             key=lambda pair: digest(pair))[:2]
        for left, right in pairs + other_pairs:
            add('relationship_type', context, {
                'first_fact': candidates[left]['canonical_value'],
                'second_fact': candidates[right]['canonical_value'],
                'instruction': 'Classify how the first fact relates to the second using source chronology and scope. Do not infer a relationship merely because the pair is shown.',
            }, {'conversation_id': conversation_id, 'source_memory_id': left,
                'target_memory_id': right, 'machine_proposal': proposed.get((left, right))})
        selected_runs = [run for run in source['runs'] if run['audit']['conversation_id'] == conversation_id]
        seen_tests = set()
        for run in selected_runs:
            tests = {test['id']: test for test in run['tests']}
            evaluations = {evaluation['test_id']: evaluation for evaluation in run['evaluations']}
            for test in tests.values():
                signature = digest([test['prompt'], test['expected_behavior'], sorted(test['supporting_memory_ids'])])
                if signature in seen_tests:
                    continue
                seen_tests.add(signature)
                add('test_validity', context, {
                    'question': test['prompt'],
                    'proposed_reference_behavior': test['expected_behavior'],
                    'instruction': 'This reference was generated by the system. Check it against the source; it is not an independent gold label.',
                    'corrected_reference_behavior': None,
                }, {'conversation_id': conversation_id, 'run_id': run['audit']['id'], 'test': test})
            for response in run['responses']:
                test = tests[response['test_id']]
                content = {'question': test['prompt'], 'proposed_reference_behavior': test['expected_behavior'],
                           'response': response['response_text'],
                           'instruction': 'Judge source-supported correctness, including explanations and invented details. Leave unresolved items blank and explain why; do not force pass/fail.',
                           'corrected_reference_behavior': None}
                private = {'conversation_id': conversation_id, 'run_id': run['audit']['id'],
                           'test_id': test['id'], 'response_id': response['id'],
                           'automated_evaluation': evaluations[test['id']]}
                add('evaluator_verdict', context, content, private)
                add('failure_dimension', context, content, private)

    fingerprint = digest({'contexts': contexts, 'items': cases})
    pilot = {
        'pilot_id': 'saved-development-double-review-v1',
        'dataset_id': 'saved-development-review-v1', 'dataset_version': fingerprint,
        'created_at': datetime.now(timezone.utc).isoformat(), 'authorised_for_research': True,
        'data_origin': 'Six synthetic development histories already executed through the GUI; not untouched held-out data.',
        'deidentification_note': 'This identifier-only readiness package contains no source text, model answers, credentials or real participant data. Separate reviewer materials contain synthetic source facts.',
        'annotation_mode': 'human_double_annotation', 'minimum_paired_items_per_task': 5,
        'minimum_kappa': 0.6,
        'items': [{'item_id': item['item_id'], 'task': item['task']} for item in cases],
        'annotators': [{'annotator_id': 'replace-with-independent-reviewer-a', 'labels': []},
                       {'annotator_id': 'replace-with-independent-reviewer-b', 'labels': []}],
        'adjudications': [],
    }
    for reviewer in ('A', 'B'):
        packet = {'dataset_id': pilot['dataset_id'], 'dataset_version': fingerprint,
                  'reviewer': f'Reviewer {reviewer} — replace with pseudonym',
                  'completed_independently_by_human': False,
                  'notice': 'Unlabelled development pilot. Work independently. No AI judgement is a human label.',
                  'contexts': contexts, 'items': cases}
        (destination / f'reviewer-{reviewer}.json').write_text(json.dumps(packet, ensure_ascii=False, indent=2) + '\n')
    (destination / 'private-item-mapping.json').write_text(json.dumps(mapping, ensure_ascii=False, indent=2) + '\n')
    (destination / 'pilot-package-blank.json').write_text(json.dumps(pilot, ensure_ascii=False, indent=2) + '\n')
    manifest = {'version': 'saved-development-review-pack-v1', 'source_sha256': digest(source),
                'dataset_version': fingerprint, 'histories': len(contexts), 'saved_audits': len(source['runs']),
                'items_per_task': dict(Counter(item['task'] for item in cases)),
                'human_labels': 0, 'held_out': False, 'blinded_fields': ['run identity', 'model', 'strategy', 'automated verdict', 'automated reason', 'proposed relationship type', 'automatic quality status'],
                'missing_reference_release': True,
                'files': {name: hashlib.sha256((destination / name).read_bytes()).hexdigest()
                          for name in ['reviewer-A.json', 'reviewer-B.json', 'private-item-mapping.json', 'pilot-package-blank.json']}}
    (destination / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n')
    return manifest


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('source', type=Path)
    parser.add_argument('destination', type=Path)
    args = parser.parse_args()
    result = build(json.loads(args.source.read_text()), args.destination)
    print(json.dumps({key: result[key] for key in ['histories', 'saved_audits', 'items_per_task', 'human_labels', 'held_out']}))
